version: '3'

services:
  api:
    build: packages/api
    image: materiel-api
    container_name: materiel-api
    restart: unless-stopped
    expose:
      - $HTTP_PORT
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST=db
      - DB_NAME=$MONGO_INITDB_DATABASE
      - HTTP_PORT=$HTTP_PORT
      - ORIGIN_HOST=web
      - TOKEN_SECRET
    depends_on:
      - db

  web:
    build: packages/web
    image: materiel-web
    container_name: materiel-web
    depends_on:
      - api

  db:
    image: mongo
    container_name: materiel-db
    user: $UID
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db

  proxy:
    image: nginx
    container_name: materiel-proxy
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - $HTTP_PORT:80
    depends_on:
      - web
