version: '3'

services:
  db:
    image: mongo
    container_name: materiel-db
    user: $UID
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=materiels
      - DB_USERNAME=krimi
      - DB_PASSWORD=root
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
